name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  jdk8:
    name: JDK8 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:8
      - run: rm -rf src/sbt-test/skip-sbt1.4
      - run: sbt test scripted
  jdk11:
    name: JDK11 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:11
      - run: rm -rf src/sbt-test/skip-sbt1.4
      - run: sbt test scripted
  jdk17:
    name: JDK17 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:17
      - run: rm -rf src/sbt-test/skip-java17+
      - run: rm -rf src/sbt-test/skip-sbt1.4
      - run: sbt test scripted

  jdk21:
    name: JDK21 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:21
      - run: rm -rf src/sbt-test/skip-java17+
      - run: sbt test scripted
  windows:
    name: Windows tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
      - run: rm -r -fo src\sbt-test\skip-sbt1.4
      - run: rm -r -fo src\sbt-test\skip-windows
      - run: sbt test-skip-windows scripted
        shell: bash
  checks:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
      - run: ./bin/scalafmt --test
